apiVersion: v1
kind: Service
metadata:
  name: semantic-backend
  labels:
    app: semantic-backend
spec:
  type: ClusterIP
  selector:
    app: semantic-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
