apiVersion: v1
kind: Service
metadata:
  name: semantic-frontend
  labels:
    app: semantic-frontend
spec:
  type: ClusterIP
  selector:
    app: semantic-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
