apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: semantic-frontend-ingress
spec:
  rules:
  - host: semantic-analysis.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: semantic-frontend
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: semantic-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: semantic-analysis.test
    http:
      paths:
      - path: /api(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: semantic-backend
            port:
              number: 8000
